version: "3"
services:
  socket_backend:
    build: .
    image: socket_backend
    container_name: socket_backend
    environment:
      DB_CONNECTION: postgres
      DB_HOST: socket_db
      DB_PORT: 5432
      DB_DATABASE: socket_test
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - ./src:/app
    command: /bin/sh -c "chmod +x ./entrypoint.sh && ./entrypoint.sh"
    ports:
      - 8000:8000
    restart: always
    extra_hosts:
      - host.docker.internal:172.17.0.1
