version: "3"
services:
  socket_backend:
    build: .
    image: socket_backend
    container_name: socket_backend
    environment:
      DB_CONNECTION: postgres
      DB_HOST: socket_db
      DB_PORT: 5432
      DB_DATABASE: socket_test
      DB_USER: postgres
      DB_PASS: postgres
    command: /bin/sh -c "chmod +x ./entrypoint.sh && ./entrypoint.sh"
    volumes:
      - ./src:/app
    depends_on:
      - socket_db
    ports:
      - 8000:8000
    restart: always
    extra_hosts:
      - host.docker.internal:172.17.0.1

  socket_db:
    image: postgres:latest
    container_name: socket_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socket_test
    tty: true
    ports:
      - 5433:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always

    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
      extra_hosts:
        - "host.docker.internal:172.17.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
